#!/usr/bin/env bash
#
# Assembles the interactive wireframe in wireframe/ into a directory that can
# be served as a static site -- GitHub Pages in CI, or any local web server.
#
# Besides copying the files, it generates requirements.js from
# docs/requirements/, so the wireframe's panel shows the title and status of
# each requirement exactly as the repository defines them today, rather than
# a copy that drifts. See docs/adr/0010-publish-an-interactive-wireframe.md.
#
# Usage: ./scripts/build-wireframe.sh [output-directory]   (default: build/wireframe)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

readonly SOURCE_DIR="wireframe"
readonly REQUIREMENTS_DIR="docs/requirements"
readonly OUTPUT_DIR="${1:-build/wireframe}"

rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"
cp "${SOURCE_DIR}"/*.html "${SOURCE_DIR}"/*.css "${SOURCE_DIR}"/*.js "${OUTPUT_DIR}/"

# One entry per requirement heading ("## FR-HOME-04 — Title"), with the status
# from the "- **Status:**" line that follows it.
{
  echo '// Generated by scripts/build-wireframe.sh from docs/requirements/. Do not edit.'
  echo 'window.REQUIREMENTS = {'
  for file in "${REQUIREMENTS_DIR}"/*.md; do
    awk -v file="$(basename "${file}")" '
      function json(value) {
        gsub(/\\/, "\\\\", value)
        gsub(/"/, "\\\"", value)
        return "\"" value "\""
      }
      /^## (FR|NFR)-[A-Z][A-Z0-9]*-[0-9][0-9] / {
        id = $2
        title = $0
        sub(/^## [^ ]+ [^ ]+ /, "", title)
        next
      }
      /^- \*\*Status:\*\*/ && id != "" {
        printf("  %s: { title: %s, status: %s, file: %s },\n", json(id), json(title), json($3), json(file))
        id = ""
      }
    ' "${file}"
  done
  echo '};'
} > "${OUTPUT_DIR}/requirements.js"

count="$(grep -c 'title:' "${OUTPUT_DIR}/requirements.js" || true)"
echo "Wireframe assembled in ${OUTPUT_DIR} (${count} requirements)."
